version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-redux
    versions:
    - 7.2.0
    - 7.2.2
    - 7.2.3
  - dependency-name: redux
    versions:
    - 4.0.5
